"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, BrainCircuit, CircleHelp, Gauge, RefreshCw, ShieldCheck, Target, WalletCards } from "lucide-react";
type Asset={symbol:string;price:number;rsi:number;support:number;resistance:number;stop:number;target:number;rr:number;score:number;maxScore:number;trend:string;status:string;reasons:string[]};
const fmt=(n:number)=>n>=1000?n.toLocaleString(undefined,{maximumFractionDigits:0}):n>=1?n.toFixed(2):n.toFixed(5);
export default function Home(){
 const [assets,setAssets]=useState<Asset[]>([]);const [selected,setSelected]=useState("BTCUSDT");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/market",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load market");setAssets(j.assets);}catch(e){setError(e instanceof Error?e.message:"Could not load market");}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[]);
 const active=useMemo(()=>assets.find(a=>a.symbol===selected)||assets[0],[assets,selected]);
 return <main className="shell">
  <header className="topbar"><div><div className="brand">CRYPTO <span>PILOT</span></div><div className="sub">Personal market intelligence • paper trading first</div></div><button className="iconbtn" onClick={load} aria-label="Refresh"><RefreshCw size={18}/></button></header>
  <section className="hero"><div><p className="eyebrow">MARKET SCANNER</p><h1>Find the setup. <span>Then decide.</span></h1><p className="heroText">The engine checks trend, momentum, volume, support/resistance and risk/reward. It does not promise profit and it does not place trades.</p></div><div className="paperCard"><WalletCards size={20}/><div><small>Paper balance</small><strong>$100.00</strong></div></div></section>
  <section className="stats"><div><span>Mode</span><b>Paper only</b></div><div><span>Timeframe</span><b>1H</b></div><div><span>Risk rule</span><b>1% max</b></div><div><span>AI calls</span><b>On demand</b></div></section>
  <section className="grid">
   <div className="panel"><div className="panelHead"><div><p className="eyebrow">LIVE WATCHLIST</p><h2>Market setups</h2></div><span className="live"><i/>LIVE</span></div>
    {loading&&!assets.length?<div className="loading">Scanning liquid markets...</div>:error?<div className="error">{error}<button onClick={load}>Retry</button></div>:<div className="assetList">{assets.map(a=><button className={"asset "+(a.symbol===selected?"active":"")} key={a.symbol} onClick={()=>setSelected(a.symbol)}><div className="coin">{a.symbol.replace("USDT","")}<small> / USDT</small></div><div className="price">{"$"+fmt(a.price)}</div><div className="mini">{a.trend}</div><div className="score">{a.score}/{a.maxScore}</div><div className={"status "+a.status.toLowerCase().replaceAll(" ","-")}>{a.status}</div></button>)}</div>}
   </div>
   <div className="panel">{active?<><div className="panelHead"><div><p className="eyebrow">SETUP ANALYSIS</p><h2>{active.symbol.replace("USDT","")} <span>/ USDT</span></h2></div><div className={"signal "+active.status.toLowerCase().replaceAll(" ","-")}>{active.status}</div></div><div className="priceBig">{"$"+fmt(active.price)} <small>{active.trend} trend</small></div><div className="metrics"><Metric icon={<Gauge size={17}/>} label="Setup score" value={active.score+"/"+active.maxScore}/><Metric icon={<Activity size={17}/>} label="RSI" value={active.rsi.toFixed(1)}/><Metric icon={<Target size={17}/>} label="R:R" value={active.rr?"1:"+active.rr.toFixed(1):"—"}/><Metric icon={<ShieldCheck size={17}/>} label="Stop" value={"$"+fmt(active.stop)}/></div><div className="levels"><Level label="Support" value={"$"+fmt(active.support)}/><Level label="Entry reference" value={"$"+fmt(active.price)}/><Level label="Target" value={"$"+fmt(active.target)}/><Level label="Resistance" value={"$"+fmt(active.resistance)}/></div><div className="evidence"><h3>Why the engine scored it this way</h3>{active.reasons.map((r,i)=><div className="reason" key={i}><span>✓</span>{r}</div>)}</div><button className="analyze" disabled><BrainCircuit size={18}/> AI analyst — coming in V5</button></>:<div className="loading">Choose a market.</div>}</div>
  </section>
  <section className="bottomGrid"><div className="panel"><p className="eyebrow">BUILD STATUS</p><h2>V1 foundation is active</h2><div className="steps"><Step n="01" title="Market data" done/><Step n="02" title="Technical engine" done/><Step n="03" title="Setup scoring" done/><Step n="04" title="Paper trading"/><Step n="05" title="AI analyst"/><Step n="06" title="Backtesting"/></div></div><div className="panel"><p className="eyebrow">SAFETY RULES</p><h2>What this assistant will never do</h2><ul><li>Guarantee a profit or invent a confidence percentage.</li><li>Automatically trade real money in V1.</li><li>Use leverage or futures by default.</li><li>Tell you to chase a coin simply because it is pumping.</li></ul><div className="note"><CircleHelp size={17}/><span>AI will explain evidence produced by the rules engine; it will not override the risk engine.</span></div></div></section>
  <footer>Crypto Pilot • Built for learning, testing and disciplined decision-making.</footer>
 </main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="metric"><span>{icon}{label}</span><b>{value}</b></div>}
function Level({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function Step({n,title,done}:{n:string;title:string;done?:boolean}){return <div className={"step "+(done?"done":"")}><b>{done?"✓":n}</b><span>{title}</span></div>}
